---
- name: Play para la instalacion y configuracion inicial de webserver
  hosts: prueba
  become: yes

  tasks:

  - name: El paquete httpd tiene que estar instalado
    ansible.builtin.dnf: 
      name: httpd
      state: present

  - name: Iniciar el daemon y dejarlo en enable
    ansible.builtin.systemd_service:
      name: httpd
      enabled: true
      state: started

  - name: Abrir los puertos para Apache
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop: 
      - http
      - https    

  - name: Archivo indice customizado
    ansible.builtin.template:
      src: ./templates/index.j2
      dest: /var/www/index.html
      owner: apache
      group: apache
      mode: u=rw,g=r,o=r

